games/urls.py
from django.urls import path
from . import views

app_name='games'

urlpatterns = [
    path('', views.join, name='join'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('<str:id>/', views.invite, name='invite'),
    path('<str:id>/<str:code>/', views.play, name='play'),
]

go/urls.py
from django.urls import path
from . import views

app_name='go'

urlpatterns = [
    path('', views.go, name='go'),
]

lotteh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views
from kick import views as kick_views
from landing import views as landing_views
from errors import views as error_views
from misc import views as misc_views
from django_summernote.urls import urlpatterns as summernote_urlpatterns
from django.conf import settings

urlpatterns = [
    path('', include(('app.urls'), namespace='app')),
    path('', include(('landing.urls'), namespace='landing')),
    path('', include(('misc.urls'), namespace='misc')),
    path('logs/', error_views.logs, name='logs'),
    path('logs/api/', error_views.logs_api, name='logs-api'),
    path('admin/login/', user_views.login),
    path('admin/', admin.site.urls),
    path('', landing_views.landing, name='/'),
    path('accounts/', include(('users.urls'), namespace='users')),
    path('feed/', include(('feed.urls'), namespace='feed')),
    path('vendors/', include(('vendors.urls'), namespace='vendors')),
    path('vibe/', include(('vibe.urls'), namespace='vibe')),
    path('live/', include(('live.urls'), namespace='live')),
    path('chat/', include(('chat.urls'), namespace='chat')),
    path('verify/', include(('verify.urls'), namespace='verify')),
    path('birthcontrol/', include(('birthcontrol.urls'), namespace='birthcontrol')),
    path('go/', include(('go.urls'), namespace='go')),
    path('security/', include(('security.urls'), namespace='security')),
    path('recordings/', include(('recordings.urls'), namespace='recordings')),
    path('interactive/', include(('interactive.urls'), namespace='interactive')),
    path('voice/', include(('voice.urls'), namespace='voice')),
    path('sms/', include(('sms.urls'), namespace='sms')),
    path('face/', include(('face.urls'), namespace='face')),
    path('kick/', include(('kick.urls'), namespace='kick')),
    path('audio/', include(('audio.urls'), namespace='audio')),
    path('tts/', include(('tts.urls'), namespace='tts')),
    path('payments/', include(('payments.urls'), namespace='payments')),
    path('recovery/', include(('recovery.urls'), namespace='recovery')),
    path('barcode/', include(('barcode.urls'), namespace='barcode')),
    path('shell/', include(('shell.urls'), namespace='shell')),
    path('hypnosis/', include(('hypnosis.urls'), namespace='hypnosis')),
    path('photobooth/', include(('photobooth.urls'), namespace='photobooth')),
    path('notifications/', include(('notifications.urls'), namespace='notifications')),
    path('survey/', include(('survey.urls'), namespace='survey')),
    path('synthesizer/', include(('synthesizer.urls'), namespace='synthesizer')),
    path('crypto/', include(('crypto.urls'), namespace='crypto')),
    path('melanin/', include(('melanin.urls'), namespace='melanin')),
    path('remote/', include(('remote.urls'), namespace='remote')),
    path('send/', include(('retargeting.urls'), namespace='retargeting')),
    path('mail/', include(('mail.urls'), namespace='mail')),
    path('contact/', include(('contact.urls'), namespace='contact')),
    path('meet/', include(('meet.urls'), namespace='meet')),
    path('games/', include(('games.urls'), namespace='games')),
    path('desktop/', include(('desktop.urls'), namespace='desktop')),
    path('appeal/', kick_views.reasess_kick, name='appeal'),
    path('password-reset-confirm/<uidb64>/<token>/', user_views.password_reset, name='password_reset_confirm'),
#         auth_views.PasswordResetConfirmView.as_view(
#             template_name='users/password_reset_confirm.html'
#         ),
#         name='password_reset_confirm'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
#    path('', include('pwa_webpush.urls')),
    path('webpush/', include('webpush.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('allauth.socialaccount.urls')),
#    path("__debug__/", include("debug_toolbar.urls")),
    path("webauth/", include("webauth.urls")),
]

handler404 = 'errors.views.handler404'
handler500 = 'errors.views.handler500'
handler403 = 'errors.views.handler403'
handler400 = 'errors.views.handler400'

title = '{} Admin Panel'.format(settings.SITE_NAME)

admin.site.site_title = title
admin.site.site_title = title
admin.site.index_title = title

games/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from feed.models import Post

class Game(models.Model):
    id = models.AutoField(primary_key=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='games')
    time = models.DateTimeField(default=timezone.now)
    player1 = models.ForeignKey(User, related_name='created_games', null=True, blank=True, on_delete=models.CASCADE)
    player2 = models.ForeignKey(User, related_name='joined_games', null=True, blank=True, on_delete=models.CASCADE)
    player1_score = models.CharField(max_length=10, default=None, null=True, blank=True)
    player2_score = models.CharField(max_length=10, default=None, null=True, blank=True)
    uid = models.CharField(max_length=10, default='')
    code = models.CharField(max_length=10, default='')
    begun = models.BooleanField(default=False)
    scored = models.BooleanField(default=False)
    players = models.IntegerField(default=0, null=True)
    turn = models.TextField(default='')
    turns = models.TextField(default='')

games/forms.py
from django import forms

class JoinForm(forms.Form):
    code = forms.IntegerField(required=False)
    def __init__(self, *args, **kwargs):
        super(JoinForm, self).__init__(*args, **kwargs)
    help_texts = {
        'code': 'Please enter the code given to you by the other player.'
    }

games/views.py
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.cache import cache_page, never_cache

def get_num_length(num, length):
    n = ''
    for x in range(length):
        n = n + str(num)
    return int(n)

@cache_page(60*5)
def leaderboard(request):
    from django.conf import settings
    from .models import Game
    from django.shortcuts import render
    board = ''
    games = Game.objects.filter(scored=True).exclude(player1=None).exclude(player2=None).order_by('-time')
    from django.core.paginator import Paginator
    from django.contrib import messages
    page = 1
    if(request.GET.get('page', '') != ''):
        page = int(request.GET.get('page', ''))
    p = Paginator(games, 50)
    if page > p.num_pages or page < 1:
        messages.warning(request, "The page you requested, " + str(page) + ", does not exist. You have been redirected to the first page.")
        page = 1
    return render(request, 'games/leaderboard.html', {
        'title': 'Game Leaderboard',
        'games': p.page(page),
        'count': p.count,
        'page_obj': p.get_page(page),
        'current_page': page,
        'description': 'See the leading players on {}'.format(settings.SITE_NAME)
    })

def invite(request, id):
    from django.urls import reverse
    from feed.models import Post
    from games.models import Game
    from django.utils import timezone
    import datetime
    import random
    from django.conf import settings
    from django.shortcuts import render, get_object_or_404, redirect
    post = Post.objects.filter(friendly_name__icontains=id).order_by('-date_posted').first()
    if not post: post = Post.objects.filter(friendly_name__icontains=id[:32]).order_by('-date_posted').first()
    if not post: post = Post.objects.filter(friendly_name__icontains=id[:24]).order_by('-date_posted').first()
    if not post: post = Post.objects.filter(friendly_name__icontains=id[:15]).order_by('-date_posted').first()
    code = str(random.randint(get_num_length(1, settings.GAME_CODE_LENGTH), get_num_length(9, settings.GAME_CODE_LENGTH)))
    user_code = str(random.randint(get_num_length(1, settings.GAME_CODE_LENGTH), get_num_length(9, settings.GAME_CODE_LENGTH)))
    while (Game.objects.filter(uid=user_code, time__gte=timezone.now() - datetime.timedelta(hours=48)).last() or Game.objects.filter(uid=user_code, time__gte=timezone.now() - datetime.timedelta(hours=48)).last()):
        code = str(random.randint(get_num_length(1, settings.GAME_CODE_LENGTH), get_num_length(9, settings.GAME_CODE_LENGTH)))
        user_code = str(random.randint(get_num_length(1, settings.GAME_CODE_LENGTH), get_num_length(9, settings.GAME_CODE_LENGTH)))
    game = Game.objects.create(post=post, uid=user_code, code=code)
    return render(request, 'games/invite.html', {'game': game, 'code': code, 'user_code': user_code, 'post': post, 'title': 'Invite Player', 'small': True})

@csrf_exempt
@never_cache
#@cache_page(60*60*24*30)
def join(request):
    from .forms import JoinForm
    from django.urls import reverse
    from games.models import Game
    from django.utils import timezone
    import datetime
#    from django.conf import settings
    from django.shortcuts import redirect
    if request.method == 'POST':
        form = JoinForm(request.POST)
        if form.is_valid():
            game = Game.objects.filter(code=form.cleaned_data.get('code', None), time__gte=timezone.now() - datetime.timedelta(hours=48)).last()
            if not game:
                from django.contrib import messages
                messages.warning(request, 'This code was not recognized. Please try again.')
                return redirect(request.path)
            game.started = True
            game.save()
            return redirect(reverse('games:play', kwargs={'id': game.post.id, 'code': game.code}))
    from django.shortcuts import render
    return render(request, 'games/join.html', {'title': 'Join Game', 'form': JoinForm(), 'small': True})

def play(request, id, code):
    from .forms import JoinForm
    from django.urls import reverse
    from games.models import Game
    from django.utils import timezone
    import datetime
    from feed.models import Post
#    from django.conf import settings
    from django.shortcuts import render, get_object_or_404, redirect
    post = get_object_or_404(Post, id=id)
    game = Game.objects.filter(post=post, code=code, time__gte=timezone.now() - datetime.timedelta(hours=48)).last()
    player = False
    if not game:
        game = Game.objects.filter(post=post, uid=code, time__gte=timezone.now() - datetime.timedelta(hours=48)).last()
        player = True
    if request.user.is_authenticated and player:
        game.player1 = request.user
        game.save()
    elif request.user.is_authenticated and not player:
        game.player2 = request.user
        game.save()
    return render(request, 'games/game.html', {'hidenavbar': True, 'title': 'Play Game', 'post': post, 'game': game, 'player': player, 'full': True, 'game_code': code, 'show_ads': False})

games/templates/games/game.html
{% extends 'base.html' %}
{% block head %}
<script src="/static/js/createjs.min.js"></script>
<style>
body {
	overflow: hidden;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;
	margin-left: 0px;
}
#main {
    overflow: hidden;
    margin-top: 0px;
    margin-right: 0px;
    margin-bottom: 0px;
    margin-left: 0px;
}
#main-container {
    overflow: hidden;
    margin-top: 0px;
    margin-right: 0px;
    margin-bottom: 0px;
    margin-left: 0px;
}
html, body, main {
    margin: 0 !important;
    padding: 0 !important;
}
</style>
{% endblock %}
{% block content %}
<canvas id="game" style="width: 100%; height: 80%;"></canvas>
{% if show_ads %}
<div class="mx-auto m-1 p-1" style="display: flex; justify-content: space-around;">
{% include 'game_ad.html' %}
</div>
{% endif %}
<p class="hide" id="player">{% if player %}y{% else %}n{% endif %}</p>
<p class="hide" id="game_id">{{ game.id }}</p>
<p class="hide" id="post_id">{{ game.post.id }}</p>
<p class="hide" id="game_code">{{ game_code }}</p>
{% autoescape off %}
<p class="hide">{{ game.post.content }}</p>
{% endautoescape %}
{% endblock %}

games/templates/games/invite.html
{% extends 'base.html' %}
{% load feed_filters %}
{% block head %}
<script src="/static/qrcode.min.js" type="text/javascript"></script>
{% endblock %}
{% block content %}
<legend>{{ 'Invite a Friend'|etrans }}</legend>
<p><i>{{ game.post.id|shorttitle|trans }}</i></p>
<div style="display: flex; justify-content: space-around;">
<img src="{{ post.get_image_thumb_url }}" alt="{{ game.post.id|shorttitle|trans }}" style="width: 60%;"/>
</div>
<legend>{{ 'Invite Code:'|etrans }} <b id="#gamecode">{{ code }}</b> <button class="btn btn-outline-info btn-sm" onclick="copyToClipboard('#gamecode');">{{ 'Copy'|etrans }}</button></legend>
<legend>{{ 'Invite URL:'|etrans }} <b id="#gameurl">{{ base_url }}/games/{{ game.post.id }}/{{ code }}/</b> <button class="btn btn-outline-info btn-sm" onclick="copyToClipboard('#gameurl');">{{ 'Copy'|etrans }}</button></legend>
<p>{{ 'Give the other player this code, and have them enter it.'|etrans }}</p>
<p><button onclick="join();" title="{{ 'Join the game'|etrans }}" class="btn btn-outline-success" id="joinButton">{{ 'Join Game'|etrans }}</button></p>
<small>{{ 'Alternatively, scan this QR code'|etrans }}</small>
<div style="display: flex; justify-content: space-around;"><div id="gameqrcode" style="border-style: solid; border-width: 15px; border-radius: 5px; border-color: #EEEEEE;"></div></div>
<hr>
<p><a title="{{ 'Accept an invite (send this link to your friend)'|etrans }}"  href="{% url 'games:join' %}">{{ 'Accept invite'|etrans }}</a> ⚬ <a title="{{ 'Visit the leaderboard'|etrans }}"  href="{% url 'games:leaderboard' %}">{{ 'Leaderboard'|etrans }}</a></p>
{% endblock %}
{% block javascript %}
var gameqrdiv = document.getElementById("gameqrcode");
var gameqr = new QRCode(gameqrdiv, "{{ base_url }}/games/{{ game.post.id }}/{{ code }}/");
var gameimage = gameqrdiv.querySelector('img');
gameimage.style.width = "100%";
gameimage.style.height = "100%";
gameimage.style.maxWidth = "160px";
gameimage.alt = "{{ 'Share this page by scanning a QR code.'|etrans }}";
function openSocket() {
	socket = new WebSocket("wss://" + window.location.hostname + '/ws/games/{{ game.post.id }}/{{ game.code }}/');
	socket.addEventListener("open", (event) => {
		console.log('Socket open.');
		setInterval(function() {
			socket.send('x');
		}, 1000);
	});
	socket.addEventListener("message", (event) => {
		if(event.data != '') {
			document.getElementById('joinButton').disabled = false;
		}
	});
	socket.addEventListener("close", (event) => {
		console.log('Socket closed.');
		setTimeout(function() {
			openSocket();
		}, {{ reload_time }});
	});
}
/*openSocket();*/
function join() {
	window.location.href = '{% url 'games:play' game.post.id game.uid %}';
}
{% endblock %}

games/templates/games/join.html
{% extends 'base.html' %}
{% load feed_filters %}
{% load crispy_forms_tags %}
{% block content %}
<legend>Join a Game</legend>
<form method="POST">
{{ form|crispy }}
<button type="submit" class="btn btn-outline-success" title="Accept invite">Join</button>
</form>
<p>Enter the code the other player gave you in order to join the game.</p>
<hr>
{% endblock %}

games/templates/games/leaderboard.html
{% extends 'base.html' %}
{% block content %}
{% load feed_filters %}
<legend>{{ 'Leaderboard'|etrans }}</legend>
<hr>
{% for game in games %}
<p>*{{ game.post.id|shorttitle|trans }}* @{{ game.player1.profile.name }} ({{ game.player1_score }}) [{{ game.player1|scoretotals }}] vs. @{{ game.player2.profile.name }} ({{ game.player2_score }}) [{{ game.player2|scoretotals }}] - {% if game.player1_score|toint == game.player2_score|toint %}{{ 'This game was a tie.'|etrans }}{% elif game.player1_score|toint < game.player2_score|toint %}{{ game.player1.profile.name }} {{ 'won with a score of'|etrans }} {{ game.player1_score }}.{% else %}{{ game.player2.profile.name }} {{ 'won with a score of'|etrans }} {{ game.player2_score }}.{% endif %}</p>
<hr>
{% endfor %}
{% endblock %}