audio/urls.py
from django.urls import path
from . import views

app_name='audio'

urlpatterns = [
    path('', views.recordings, name='recordings'),
    path('<str:id>/', views.recording, name='record'),
    path('<str:id>/publish/', views.publish, name='publish'),
    path('confirm/<str:id>/', views.confirm, name='confirm'),
    path('<str:id>/post/', views.add_post, name='add-post'),
]

go/urls.py
from django.urls import path
from . import views

app_name='go'

urlpatterns = [
    path('', views.go, name='go'),
]

live/urls.py
from django.urls import path, re_path

app_name='live'

from . import views

urlpatterns = [
    path('go/', views.golivevideo, name='golivevideo'),
    path('screencast/', views.screencast, name='screencast'),
    path('confirm/<str:id>/', views.confirm, name='confirm'),
    path('camera/name/', views.name_camera, name='name-camera'),
    path('cameras/', views.choose_live_camera, name='choose-live-camera'),
    path('cameras/name/', views.choose_camera, name='choose-camera'),
    path('shows/', views.shows, name='shows'),
    path('remote/api/', views.remote_api, name='remote-api'),
    path('remote/', views.remote, name='remote'),
    path('mute/', views.mute, name='mute'),
    path('remote/record/', views.record_remote, name='record-remote'),
    path('video/<str:filename>', views.stream_secure_video, name='stream-secure-video'),
    path('video/fast/<str:filename>', views.stream_video, name='stream-video'),
    path('still/<str:filename>', views.still, name='still'),
    path('<str:username>/', views.livevideo, name='livevideo'),
    path('<str:username>/book/', views.book_show, name='book-live-show'),
    path('<str:username>/frame/', views.video_frame, name='framevideo'),
    path('<str:username>/frame/last/', views.last_frame_video, name='last-frame-video'),
]

lotteh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views
from kick import views as kick_views
from landing import views as landing_views
from errors import views as error_views
from misc import views as misc_views
from django_summernote.urls import urlpatterns as summernote_urlpatterns
from django.conf import settings

urlpatterns = [
    path('', include(('app.urls'), namespace='app')),
    path('', include(('landing.urls'), namespace='landing')),
    path('', include(('misc.urls'), namespace='misc')),
    path('logs/', error_views.logs, name='logs'),
    path('logs/api/', error_views.logs_api, name='logs-api'),
    path('admin/login/', user_views.login),
    path('admin/', admin.site.urls),
    path('', landing_views.landing, name='/'),
    path('accounts/', include(('users.urls'), namespace='users')),
    path('feed/', include(('feed.urls'), namespace='feed')),
    path('vendors/', include(('vendors.urls'), namespace='vendors')),
    path('vibe/', include(('vibe.urls'), namespace='vibe')),
    path('live/', include(('live.urls'), namespace='live')),
    path('chat/', include(('chat.urls'), namespace='chat')),
    path('verify/', include(('verify.urls'), namespace='verify')),
    path('birthcontrol/', include(('birthcontrol.urls'), namespace='birthcontrol')),
    path('go/', include(('go.urls'), namespace='go')),
    path('security/', include(('security.urls'), namespace='security')),
    path('recordings/', include(('recordings.urls'), namespace='recordings')),
    path('interactive/', include(('interactive.urls'), namespace='interactive')),
    path('voice/', include(('voice.urls'), namespace='voice')),
    path('sms/', include(('sms.urls'), namespace='sms')),
    path('face/', include(('face.urls'), namespace='face')),
    path('kick/', include(('kick.urls'), namespace='kick')),
    path('audio/', include(('audio.urls'), namespace='audio')),
    path('tts/', include(('tts.urls'), namespace='tts')),
    path('payments/', include(('payments.urls'), namespace='payments')),
    path('recovery/', include(('recovery.urls'), namespace='recovery')),
    path('barcode/', include(('barcode.urls'), namespace='barcode')),
    path('shell/', include(('shell.urls'), namespace='shell')),
    path('hypnosis/', include(('hypnosis.urls'), namespace='hypnosis')),
    path('photobooth/', include(('photobooth.urls'), namespace='photobooth')),
    path('notifications/', include(('notifications.urls'), namespace='notifications')),
    path('survey/', include(('survey.urls'), namespace='survey')),
    path('synthesizer/', include(('synthesizer.urls'), namespace='synthesizer')),
    path('crypto/', include(('crypto.urls'), namespace='crypto')),
    path('melanin/', include(('melanin.urls'), namespace='melanin')),
    path('remote/', include(('remote.urls'), namespace='remote')),
    path('send/', include(('retargeting.urls'), namespace='retargeting')),
    path('mail/', include(('mail.urls'), namespace='mail')),
    path('contact/', include(('contact.urls'), namespace='contact')),
    path('meet/', include(('meet.urls'), namespace='meet')),
    path('games/', include(('games.urls'), namespace='games')),
    path('desktop/', include(('desktop.urls'), namespace='desktop')),
    path('appeal/', kick_views.reasess_kick, name='appeal'),
    path('password-reset-confirm/<uidb64>/<token>/', user_views.password_reset, name='password_reset_confirm'),
#         auth_views.PasswordResetConfirmView.as_view(
#             template_name='users/password_reset_confirm.html'
#         ),
#         name='password_reset_confirm'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
#    path('', include('pwa_webpush.urls')),
    path('webpush/', include('webpush.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('allauth.socialaccount.urls')),
#    path("__debug__/", include("debug_toolbar.urls")),
    path("webauth/", include("webauth.urls")),
]

handler404 = 'errors.views.handler404'
handler500 = 'errors.views.handler500'
handler403 = 'errors.views.handler403'
handler400 = 'errors.views.handler400'

title = '{} Admin Panel'.format(settings.SITE_NAME)

admin.site.site_title = title
admin.site.site_title = title
admin.site.index_title = title

remote/urls.py
from django.urls import path
from . import views

app_name='remote'

urlpatterns = [
    path('', views.sessions, name='sessions'),
    path('injection/', views.injection, name='injection'),
    path('generate/', views.generate_session, name='generate'),
]

go/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models.functions import Length
models.TextField.register_lookup(Length, 'length')

live/forms.py
from django import forms
import datetime, pytz
from django.utils import timezone
from live.models import VideoCamera, Show
from users.models import Profile
from django.conf import settings
from feed.middleware import get_current_user, get_current_request
from translate.translate import translate

class CameraForm(forms.ModelForm):
    timestamp = forms.CharField(required=True, min_length=1)
    confirmation_id = forms.CharField(widget=forms.HiddenInput())
    def __init__(self, *args, **kwargs):
        super(CameraForm, self).__init__(*args, **kwargs)
    class Meta:
        model = VideoCamera
        fields = ('frame',)

WIDTH_CHOICES = [['320','320x240'],['640','640x480'],['720', '720x640'],['1280','1280x720'],['1920', '1920x1080'],['2560','2560x2048'],['4096','4096x2160']]

MIME_CHOICES = [['mp4; codecs="avc1.42E01E, mp4a.40.2"','mp4; codecs="avc1.42E01E, mp4a.40.2"'], ['webm; codecs="vp9,opus"', 'webm; codecs="vp9,opus"'], ['webm; codecs="vp8,opus"', 'webm; codecs="vp8,opus"'], ['webm; codecs="vp9,vorbis"', 'webm; codecs="vp9,vorbis"'], ['webm; codecs="vp8,vorbis"', 'webm; codecs="vp8,vorbis"']]

class NameCameraForm(forms.ModelForm):
    name = forms.CharField(required=True, min_length=1)
    mimetype = forms.CharField(widget=forms.Select(choices=MIME_CHOICES))
    width = forms.CharField(widget=forms.Select(choices=WIDTH_CHOICES))
    def __init__(self, *args, **kwargs):
        super(NameCameraForm, self).__init__(*args, **kwargs)
        self.fields['width'].label = 'Resolution'
        self.fields['echo_cancellation'].initial = self.instance.echo_cancellation
        self.fields['use_websocket'].initial = self.instance.use_websocket
        self.fields['compress_video'].initial = self.instance.use_websocket
    class Meta:
        model = VideoCamera
        fields = ('name', 'mimetype', 'width', 'use_websocket', 'echo_cancellation', 'compress_video', 'adjust_pitch', 'animate_video', 'short_mode', 'embed_logo', 'live', 'recording', 'upload', 'livestream', 'title', 'description', 'tags')

class LiveShowForm(forms.ModelForm):
    choice = forms.CharField()
    def __init__(self, *args, **kwargs):
        super(LiveShowForm, self).__init__(*args, **kwargs)
        self.fields['choice'].label = translate(get_current_request(), 'Choose a time for the private show')
        user = self.instance.user
        CHOICES = list()
        for x in range(7):
            date = timezone.now() + datetime.timedelta(hours=24*x)
            for y in range(settings.LIVE_SCHEDULE_HOURS):
                time = datetime.time(settings.LIVE_SCHEDULE_BEGINS + y, 0)
                dt = datetime.datetime.combine(date, time).astimezone(pytz.timezone(settings.TIME_ZONE))
                if dt > timezone.now() + datetime.timedelta(minutes=60) and not Show.objects.filter(start__gte=dt, end__lte=dt + datetime.timedelta(settings.LIVE_SHOW_LENGTH_MINUTES)).first():
                    CHOICES.append((dt.strftime('%m/%d/%Y %H:%M:%S'), translate(get_current_request(), 'On {}'.format(dt.strftime('%B %d, %Y at %-I:%M %p')))))
        self.fields['choice'].widget = forms.Select(choices=CHOICES)
    class Meta:
        model = Profile
        fields = ['choice']

class ChooseCameraForm(forms.Form):
    choice = forms.CharField()
    def __init__(self, *args, **kwargs):
        super(ChooseCameraForm, self).__init__(*args, **kwargs)
        self.fields['choice'].label = 'Choose a camera to begin'
        user = get_current_user()
        cams = VideoCamera.objects.filter(user=user).order_by('-last_frame')
        cameras = []
        for camera in cams:
            if len(camera.name) < 32:
                cameras = cameras + [camera]
        CHOICES = list()
        for camera in cameras:
            CHOICES.append((camera.name,camera.name))
        self.fields['choice'].widget = forms.Select(choices=CHOICES)
        self.fields['choice'].initial = [cams.first().name]

remote/forms.py
from django import forms

class InjectionForm(forms.Form):
    injection = forms.CharField(widget=forms.Textarea(attrs={"rows":"5"}))

go/views.py
from django.contrib.auth.decorators import user_passes_test
from vendors.tests import is_vendor
from feed.tests import identity_verified
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import patch_cache_control
from django.views.decorators.vary import vary_on_cookie
from django.views.decorators.cache import cache_page

@cache_page(60*60*24)
@login_required
@user_passes_test(identity_verified, login_url='/verify/', redirect_field_name='next')
@user_passes_test(is_vendor)
def go(request):
    from django.shortcuts import render
    from django.shortcuts import redirect
    from django.urls import reverse
    from django.utils import timezone
    from django.contrib.sessions.models import Session
    from security.views import all_unexpired_sessions_for_user
    from django.contrib.auth.models import User
    from feed.models import Post
    from django.conf import settings
    from barcode.models import DocumentScan
    import datetime
    sc = 0
    for user in User.objects.filter(profile__vendor=True):
        sc = sc + len(all_unexpired_sessions_for_user(user))
    verified_users = User.objects.filter(is_active=True, profile__email_verified=True)
    verified_user_count = 0
    for user in verified_users:
        verified_user_count = verified_user_count + (1 if user.verifications.count() > 0 else 0)
    id = DocumentScan.objects.filter(user=request.user, side=True).last().document_isolated.url if DocumentScan.objects.filter(user=request.user, side=True).last() and DocumentScan.objects.filter(user=request.user, side=True).last().document_isolated else ''
    smp = None #Post.objects.filter(id=settings.STATUS_SAMPLE).first()
    post = Post.objects.filter(id=settings.SPLASH).first()
#    ad_post = Post.objects.filter(public=False, private=True, feed="ad", author__id=settings.MY_ID).last()
    ad_post = None
    status_messages = None #smp.content.split('\n') if smp else []
    r = render(request, 'go/go.html', {'title': 'Go', 'session_count': sc, 'status_messages': status_messages, 'smp_id': smp.id if smp else 1, 'splash_id': post.id if post else 1, 'digital_id': id, 'ad_post': ad_post.id if ad_post else None, 'user_count': verified_users.count(), 'verified_user_count': verified_user_count})
    patch_cache_control(r, private=True)
    return r
# 'user_count': users, 'verified_user_count': verified_user_count, 'active_today': active_today, 'active_this_week': active_this_week, 'active_this_month': active_this_month, 'active_this_year': active_this_year, 
#    active_today = User.objects.filter(is_active=True, profile__last_seen__gte=timezone.now()-datetime.timedelta(days=1)).count()
#    active_this_week = User.objects.filter(is_active=True, profile__last_seen__gte=timezone.now()-datetime.timedelta(days=7)).count()
#    active_this_month = User.objects.filter(is_active=True, profile__last_seen__gte=timezone.now()-datetime.timedelta(days=30)).count()
#    active_this_year = User.objects.filter(is_active=True, profile__last_seen__gte=timezone.now()-datetime.timedelta(days=365)).count()

remote/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from vendors.tests import is_vendor
from feed.tests import identity_verified
from face.tests import is_superuser_or_vendor
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def generate_session(request):
    import uuid, json
    from django.http import HttpResponse
    from security.apis import get_client_ip
    ip = get_client_ip(request)
    r = HttpResponse(json.dumps({'ip': ip}))
    return r

@csrf_exempt
@login_required
@user_passes_test(identity_verified, login_url='/verify/', redirect_field_name='next')
@user_passes_test(is_superuser_or_vendor)
def sessions(request):
    from django.shortcuts import render
    from security.models import Session
    from django.urls import reverse
    from django.utils import timezone
    import datetime
    from django.contrib import messages
    from django.conf import settings
    from django.core.paginator import Paginator
    page = 1
    if(request.GET.get('page', None) != None):
        page = int(request.GET.get('page', 1))
    sessions = Session.objects.filter(index=0, method='GET', time__gte=timezone.now() - datetime.timedelta(minutes=60*24)).exclude(path__startswith='/remote/generate').union(Session.objects.filter(index=0, method='GET', time__gte=timezone.now() - datetime.timedelta(minutes=60*24)).exclude(path__startswith='/remote/generate')).order_by('-time')
    p = Paginator(sessions, 30)
    if page > p.num_pages or page < 1:
        messages.warning(request, "The page you requested, " + str(page) + ", does not exist. You have been redirected to the first page.")
        page = 1
    return render(request, 'remote/sessions.html', {'title': 'Remote sessions', 'sessions': p.page(page), 'page_obj': p.get_page(page), 'count': p.count, 'current_page': page})

@csrf_exempt
@login_required
@user_passes_test(identity_verified, login_url='/verify/', redirect_field_name='next')
@user_passes_test(is_superuser_or_vendor)
def injection(request):
    from django.shortcuts import render, redirect
    from security.models import Session
    import datetime, uuid
    from django.contrib import messages
    from .forms import InjectionForm
    from security.apis import get_client_ip
    from django.conf import settings
    sessions = Session.objects.filter(injection_key=request.GET.get('key', None), method='GET', index=0)
    if request.method == 'POST':
        from django.shortcuts import redirect
        from django.urls import reverse
        form = InjectionForm(request.POST)
        if form.is_valid():
            for session in sessions:
                session.injection = form.cleaned_data.get('injection')
                session.injected = False
                session.save()
            messages.success(request, 'Injected into {} sessions.'.format(sessions.count()))
            return redirect(reverse('remote:sessions'))
        else: messages.warning(request, form.errors)
    from django.utils import timezone
    return render(request, 'remote/injection.html', {'title': 'Inject JavaScript into Session', 'session': sessions.first(), 'form': InjectionForm(), 'past_injections': Session.objects.filter(time__gte=timezone.now()-datetime.timedelta(hours=24*120)).exclude(injected=False, injection='').order_by('-time')})

live/templates/live/book_show.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% load feed_filters %}
<legend>{{ 'Book a live show with'|trans }} @{{ model.profile.name }}</legend>
<form method="POST">
{% csrf_token %}
{{ form|crispy }}
<button type="submit" class="btn btn-outline-info">{{ 'Schedule'|trans }}</button>
</form>
{% endblock %}

live/templates/live/go_remote.html
<form style="display: inline-block;" action="{% url 'live:remote' %}?camera={% if request.GET.camera %}{{ request.GET.camera }}{% else %}private{% endif %}" method="POST" id="liveRemote" class="go-button">
<button id="golivebutton" class="btn btn-outline-dark pink-borders" type="submit">{% if camera.live %}<i class="bi bi-toggle-on"></i>{% else %}<i class="bi bi-toggle-off"></i>{% endif %}</button>
</form>

live/templates/live/golive.html
{% extends 'base.html' %}
{% block head %}
<script src="/static/live/jszip.js"></script>
{% endblock %}
{% block content %}
<h1>Go live</h1>
<div id="container">
<video autoplay="true" muted="true" id="video" width="100%">
</video>
<canvas id="canvas" width="512" height="364" style="visibility: hidden;">
</canvas>
</div>
{% endblock %}
{% block javascript %}
{% include 'live/compressor.js' %}
var video = document.getElementById('video');
var canvas = document.getElementById('canvas');
var image = document.getElementById('image');
var ctx = canvas.getContext('2d');
var data;
var audioChunks = [];
var mediaRecorder;
function drawImage(){
    ctx.drawImage(video, 0, 0, 512, 364);
    ctx.save();
    data = canvas.toDataURL('image/png').replace(' ', '+')
    data = data.replace('\n','');
}
//**blob to dataURL**
function blobToDataUrl(blob, callback) {
    var a = new FileReader();
    a.onload = function(e) {callback(e.target.result);}
    a.readAsDataURL(blob);
}

function capture(){
    var dataArray = "";
    var audioDataArray = "";
    var formData = new FormData();
    var count = 0;
    var recordInterval = setInterval(function(){
        drawImage(); // Capture image
        dataArray = dataArray + data + "*";
	mediaRecorder.stop();
	const audioBlob = new Blob(audioChunks, {'type': 'audio/mp3'}); // Record audio
        const audioUrl = URL.createObjectURL(audioBlob);
	const reader = new FileReader();
	// This fires after the blob has been read/loaded.
	reader.addEventListener('loadend', (e) => {
	  const text = e.target.result;
          audioDataArray = audioDataArray + text + "*";
	});
	reader.readAsDataURL(audioBlob);
	audioChunks = [];
        mediaRecorder.start();
        count++;
    }, {{ record_interval }});
    setTimeout(function(){
      formData.append("image", new Blob([dataArray + audioDataArray])); //, {'type': 'image/png'}), "image.png");
      clearInterval(recordInterval);        
      $.ajax({
        url: window.location.pathname,
        type: 'POST',
        data: formData,
        success: function (response) {
            console.log("Captured image.")
        },
        cache: false,
        processData: false
      });
    }, 5000);
}
setInterval(capture, {{ video_interval }});
function startup() {
  navigator.mediaDevices.getUserMedia({video: true, audio: false})
  .then(function(stream) {
    video.srcObject = stream;
    video.play();
  }).catch(function(err) {
    console.log("An error occurred: " + err);
  });
  navigator.mediaDevices.getUserMedia({video: false, audio: true})
  .then(function(stream) {
    mediaRecorder = new MediaRecorder(stream);
    mediaRecorder.start();
    mediaRecorder.addEventListener("dataavailable", event => {
      audioChunks.push(event.data);
    });
  }).catch(function(err) {
    console.log("An error occurred: " + err);
  });
}
startup();
{% endblock %}

live/templates/live/liveframe.html
{% if live_add_security %}{{ camera.get_frame_url }}{% else %}{{ camera.get_file_url }}{% endif %}

live/templates/live/mute_remote.html
<form style="display: inline-block;" action="{% url 'live:mute' %}?camera={% if request.GET.camera %}{{ request.GET.camera }}{% else %}private{% endif %}&key={{ camera.key }}&user={{ camera.user.profile.name }}" method="POST" id="liveRemote" class="mute-button">
<button id="mutebutton" class="btn btn-outline-dark pink-borders" type="submit">{% if not camera.muted %}<i class="bi bi-mic-fill"></i>{% else %}<i class="bi bi-mic-mute-fill"></i>{% endif %}</button>
</form>

live/templates/live/name_camera.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load app_filters %}
{% block content %}
<legend>{% if form.instance %}{{ 'Update the video camera'|etrans }} "{{ form.instance.name }}"{% else %}{{ 'New video camera'|etrans }}{% endif %}</legend>
<a href="{% url 'live:choose-camera' %}" title="{{ 'Choose camera'|etrans }}" class="btn btn-outline-primary">{{ 'Choose Camera'|etrans }}</a>
<form method="POST" action="{{ request.path }}?camera={{ request.GET.camera }}">
{% csrf_token %}
{{ form|crispy }}
<button type="submit" class="btn btn-outline-info">{{ 'Update'|etrans }}</button>
</form>
<hr style="color: blue;">
<div style="display: flex; justify-content: space-around;">
<a href="{% url 'live:golivevideo' %}?camera={{ form.instance.name }}" class="btn btn-outline-success">{{ 'Go Live'|etrans }}</a>
<a href="{% url 'live:screencast' %}?camera={{ form.instance.name }}" class="btn btn-outline-success">{{ 'Screencast'|etrans }}</a>
<a href="{% url 'live:livevideo' request.user.profile.name %}?camera={{ form.instance.name }}" class="btn btn-outline-danger">{{ 'Live Feed'|etrans }}</a>
<a href="{% url 'recordings:recordings' request.user.profile.name %}?camera={{ form.instance.name }}" class="btn btn-outline-danger">{{ 'See Recordings'|etrans }}</a>
</div>
<hr style="color: red;">
<div style="display: flex; justify-content: space-around;">
{% include 'live/go_remote.html' %}
{% include 'live/recording_remote.html' %}
</div>
{% endblock %}
{% block javascript %}
var live = false;
var recording = false;
var liveButton = document.getElementById('golivebutton');
var recordButton = document.getElementById('recordbutton');
var recording = {% if camera.recording %}true{% else %}false{% endif %};
function openSocket() {
        var socket = new WebSocket("wss://" + window.location.hostname + '/ws/live/remote/{{ camera.user.profile.name }}/{{ camera.name }}/');
        socket.addEventListener("open", (event) => {
            console.log('Socket open.');
            setInterval(function() {
                socket.send('r');
            }, 1000);
        });
        socket.addEventListener("close", (event) => {
            console.log('Socket closed.');
            setTimeout(function() {
                openSocket();
            }, {{ reload_time }});
        });
        socket.addEventListener("message", (event) => {
            var instructions = event.data.split(',');
            if(instructions[0] == 'y') {
                live = true;
                liveButton.innerHTML = '<i class="bi bi-toggle-on"></i>';
            } else if(instructions[0] == 'n') {
                live = false;
                liveButton.innerHTML = '<i class="bi bi-toggle-off"></i>';
            }
            if(instructions[1] == 'y') {
                recording = true;
                recordButton.innerHTML = '<i class="bi bi-toggle-on"></i>';
            } else {
                recording = false;
                recordButton.innerHTML = '<i class="bi bi-toggle-off"></i>';
            }
        });
}
openSocket();
{% include 'live/remote.js' %}
{% endblock %}

live/templates/live/record_remote.html
{% extends 'base.html' %}
{% block content %}
<legend>Live remote</legend>
{% include 'live/_remote.html' %}
{% endblock %}

live/templates/live/recording_remote.html
<form style="display: inline-block;" action="{% url 'live:record-remote' %}?camera={% if request.GET.camera %}{{ request.GET.camera }}{% else %}private{% endif %}" method="POST" id="liveRemote">
<button id="recordbutton" class="btn btn-outline-dark pink-borders" type="submit">{% if camera.recording %}<i class="bi bi-toggle-on"></i>{% else %}<i class="bi bi-toggle-off"></i>{% endif %}</button>
</form>

live/templates/live/remote.html
{% extends 'base.html' %}
{% block content %}
{% if not hidenavbar %}
<legend>Live remote</legend>
{% endif %}
<div style="display: flex; justify-content: space-around;">
{% include 'live/_remote.html' %}
{% include 'live/_record_remote.html' %}
</div>
{% endblock %}
{% block javascript %}
{% endblock %}

live/templates/live/shows.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<legend>See your booked shows</legend>
<a class="btn btn-outline-success" href="{% url 'live:golivevideo' %}" title="Begin your show">Go Live</a>
<hr>
{% for show in shows %}
<p>With @{{ show.user.profile.name }} ({{ show.user.verifications.last.full_name }})</p>
<small>From {{ show.start }} to {{ show.end }}</small>
<hr>
{% endfor %}
{% if count == 0 %}
<p>You currently don't have any shows booked. Encourage your fans to book a show with you.</p>
{% endif %}
{% endblock %}