go/urls.py
from django.urls import path
from . import views

app_name='go'

urlpatterns = [
    path('', views.go, name='go'),
]

lotteh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views
from kick import views as kick_views
from landing import views as landing_views
from errors import views as error_views
from misc import views as misc_views
from django_summernote.urls import urlpatterns as summernote_urlpatterns
from django.conf import settings

urlpatterns = [
    path('', include(('app.urls'), namespace='app')),
    path('', include(('landing.urls'), namespace='landing')),
    path('', include(('misc.urls'), namespace='misc')),
    path('logs/', error_views.logs, name='logs'),
    path('logs/api/', error_views.logs_api, name='logs-api'),
    path('admin/login/', user_views.login),
    path('admin/', admin.site.urls),
    path('', landing_views.landing, name='/'),
    path('accounts/', include(('users.urls'), namespace='users')),
    path('feed/', include(('feed.urls'), namespace='feed')),
    path('vendors/', include(('vendors.urls'), namespace='vendors')),
    path('vibe/', include(('vibe.urls'), namespace='vibe')),
    path('live/', include(('live.urls'), namespace='live')),
    path('chat/', include(('chat.urls'), namespace='chat')),
    path('verify/', include(('verify.urls'), namespace='verify')),
    path('birthcontrol/', include(('birthcontrol.urls'), namespace='birthcontrol')),
    path('go/', include(('go.urls'), namespace='go')),
    path('security/', include(('security.urls'), namespace='security')),
    path('recordings/', include(('recordings.urls'), namespace='recordings')),
    path('interactive/', include(('interactive.urls'), namespace='interactive')),
    path('voice/', include(('voice.urls'), namespace='voice')),
    path('sms/', include(('sms.urls'), namespace='sms')),
    path('face/', include(('face.urls'), namespace='face')),
    path('kick/', include(('kick.urls'), namespace='kick')),
    path('audio/', include(('audio.urls'), namespace='audio')),
    path('tts/', include(('tts.urls'), namespace='tts')),
    path('payments/', include(('payments.urls'), namespace='payments')),
    path('recovery/', include(('recovery.urls'), namespace='recovery')),
    path('barcode/', include(('barcode.urls'), namespace='barcode')),
    path('shell/', include(('shell.urls'), namespace='shell')),
    path('hypnosis/', include(('hypnosis.urls'), namespace='hypnosis')),
    path('photobooth/', include(('photobooth.urls'), namespace='photobooth')),
    path('notifications/', include(('notifications.urls'), namespace='notifications')),
    path('survey/', include(('survey.urls'), namespace='survey')),
    path('synthesizer/', include(('synthesizer.urls'), namespace='synthesizer')),
    path('crypto/', include(('crypto.urls'), namespace='crypto')),
    path('melanin/', include(('melanin.urls'), namespace='melanin')),
    path('remote/', include(('remote.urls'), namespace='remote')),
    path('send/', include(('retargeting.urls'), namespace='retargeting')),
    path('mail/', include(('mail.urls'), namespace='mail')),
    path('contact/', include(('contact.urls'), namespace='contact')),
    path('meet/', include(('meet.urls'), namespace='meet')),
    path('games/', include(('games.urls'), namespace='games')),
    path('desktop/', include(('desktop.urls'), namespace='desktop')),
    path('appeal/', kick_views.reasess_kick, name='appeal'),
    path('password-reset-confirm/<uidb64>/<token>/', user_views.password_reset, name='password_reset_confirm'),
#         auth_views.PasswordResetConfirmView.as_view(
#             template_name='users/password_reset_confirm.html'
#         ),
#         name='password_reset_confirm'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
#    path('', include('pwa_webpush.urls')),
    path('webpush/', include('webpush.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('allauth.socialaccount.urls')),
#    path("__debug__/", include("debug_toolbar.urls")),
    path("webauth/", include("webauth.urls")),
]

handler404 = 'errors.views.handler404'
handler500 = 'errors.views.handler500'
handler403 = 'errors.views.handler403'
handler400 = 'errors.views.handler400'

title = '{} Admin Panel'.format(settings.SITE_NAME)

admin.site.site_title = title
admin.site.site_title = title
admin.site.index_title = title

retargeting/urls.py
from django.urls import path
from . import views

app_name='retargeting'

urlpatterns = [
    path('email/', views.send_email, name='email'),
    path('emails/', views.emails, name='emails'),
    path('qrcode/', views.qrcode, name='qrcode')
]

retargeting/models.py
from simple_history.models import HistoricalRecords
from django.contrib import admin
from django.db import models
from django.utils import timezone
import datetime
from django.contrib.auth.models import User


class ScheduledEmail(models.Model):
    id = models.AutoField(primary_key=True)
    sender = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='scheduled_emails', null=True, blank=True)
    recipient = models.CharField(blank=True, max_length=255)
    subject = models.CharField(blank=True, max_length=255)
    content = models.TextField(blank=True)
    send_at = models.DateTimeField(default=timezone.now)
    sent = models.BooleanField(default=False)
    history = HistoricalRecords()

    def send(self):
        from users.username_generator import generate_username as get_random_username
        from users.email import send_html_email_template, send_html_email_backend, send_html_email_backend_template
        if self.sent: return
        if len(self.recipient.replace(' ','').split(',')) > 1:
            for recipient in self.recipient.replace(' ','').split(','):
                if not User.objects.filter(email=recipient).count():
                    from users.models import Profile
                    from security.models import SecurityProfile
                    user = User.objects.create_user(email=recipient, username=get_random_username(e), password=get_random_string(8))
                    if not hasattr(user, 'profile'):
                        p = Profile.objects.get_or_create(user=user)
                        p.email_verified = False
                        p.finished_signup = False
                        p.subscribed = True
                        p.save()
                    if not hasattr(user, 'security_profile'):
                        SecurityProfile.objects.get_or_create(user=user)
                user = User.objects.filter(email=recipient).order_by('-date_posted')
                if user.subscribed:
                    send_html_email_backend(self.sender, recipient, self.subject, self.content)
        elif self.recipient:
            send_html_email_backend(self.sender, self.recipient, self.subject, self.content)
        else:
            users = User.objects.filter(is_active=True, profile__email_verified=True, profile__subscribed=True)
            for user in users:
                send_html_email_template(user, self.subject, self.content)
        self.sent = True
        self.save()


class ScheduledUserEmail(models.Model):
    id = models.AutoField(primary_key=True)
    recipient = models.ForeignKey(User, null=True, blank=True, related_name='scheduled_emails_inbox', on_delete=models.CASCADE)
    subject = models.CharField(blank=True, max_length=255)
    content = models.TextField(blank=True)
    send_at = models.DateTimeField(default=timezone.now)
    sent = models.BooleanField(default=False)
    history = HistoricalRecords()

    def send(self):
        from users.email import send_html_email_template, send_email
        if self.sent: return
        if self.recipient:
            send_html_email_template(self.recipient, self.subject, self.content)
        self.sent = True
        self.save()


retargeting/forms.py
from django import forms
import datetime
from django.utils import timezone
from .models import ScheduledEmail
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
from django.core.validators import MinLengthValidator

class EmailForm(forms.ModelForm):
    date = forms.DateField(initial=datetime.date.today, widget=forms.DateInput(attrs={'type': 'date'}))
    time = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time', 'format': '%H:%M'}))
    content = forms.CharField(required=True, widget=SummernoteWidget(attrs={'rows': 9, 'style': 'background-color: #55555 !important;'}), validators=[MinLengthValidator(20)], max_length=500)
    subject = forms.CharField(required=True, validators=[MinLengthValidator(10)], max_length=60)

    class Meta:
        model = ScheduledEmail
        fields = ('subject', 'content', 'date', 'time')

retargeting/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from vendors.tests import is_vendor
from feed.tests import identity_verified
from face.tests import is_superuser_or_vendor

def qrcode(request):
    from django.shortcuts import render
    return render(request, 'retargeting/qrcode.html', {'title': 'QR Code', 'description': 'Generate a QR code'})

@login_required
@user_passes_test(identity_verified, login_url='/verify/', redirect_field_name='next')
@user_passes_test(is_superuser_or_vendor)
def emails(request):
    from django.shortcuts import render
    from django.utils import timezone
    from .models import ScheduledEmail
    sent = request.GET.get('sent', False)
    emails = ScheduledEmail.objects.filter(sender=request.user, sent=False, send_at__gte=timezone.now()).order_by('-send_at') if not sent else ScheduledEmail.objects.filter(sender=request.user, sent=True, send_at__lte=timezone.now()).order_by('-send_at')
    return render(request, 'retargeting/emails.html', {'title': 'Scheduled Emails', 'emails': emails})

@login_required
@user_passes_test(identity_verified, login_url='/verify/', redirect_field_name='next')
@user_passes_test(is_superuser_or_vendor)
def send_email(request):
    from django.shortcuts import render
    from django.shortcuts import redirect
    from django.urls import reverse
    from django.utils import timezone
    from django.contrib.auth.models import User
    from feed.models import Post
    from django.conf import settings
    import datetime, pytz
    from .forms import EmailForm
    from .models import ScheduledEmail
    from django.contrib import messages
    id = request.GET.get('id', None)
    email = None
    if id: email = ScheduledEmail.objects.filter(id=int(id)).first()
    if request.method == 'POST' and request.user.profile.can_like < timezone.now() - datetime.timedelta(seconds=2) and (not email or not email.sent):
        form = EmailForm(request.POST, instance=email)
        if form.is_valid():
            email = form.save()
            try:
                email.send_at = datetime.datetime.combine(datetime.datetime.strptime(form.data.get('date'), '%Y-%m-%d').date(), datetime.datetime.strptime(form.data.get('time'), '%H:%M:%S.%f').time())
            except:
                try:
                    email.send_at = datetime.datetime.combine(datetime.datetime.strptime(form.data.get('date'), '%Y-%m-%d').date(), datetime.datetime.strptime(form.data.get('time'), '%H:%M:%S').time())
                except:
                    try:
                        email.send_at = datetime.datetime.combine(datetime.datetime.strptime(form.data.get('date'), '%Y-%m-%d').date(), datetime.datetime.strptime(form.data.get('time'), '%H:%M').time())
                    except: email.send_at = timezone.now()
            email.recipient = request.GET.get('u', '') if request.GET.get('u', None) else ''
            email.sender = request.user
            email.save()
            messages.success(request, 'This email has been scheduled.')
            request.user.profile.can_like = timezone.now()
            request.user.profile.save()
        else: messages.warning(request, str(form.errors))
    send_at = timezone.now() + datetime.timedelta(minutes=60 * 3) if not request.GET.get('u', False) else timezone.now()
    form = EmailForm(instance=email, initial={'time': send_at.astimezone(pytz.timezone(settings.TIME_ZONE)).strftime('%H:%M:00'), 'date': send_at.astimezone(pytz.timezone(settings.TIME_ZONE)).date})
    return render(request, 'retargeting/send_email.html', {'title': 'Send Email', 'form': form, 'full': True})

retargeting/templates/retargeting/emails.html
{% extends 'base.html' %}
{% block content %}
<legend>Scheduled Emails</legend>
{% if emails.count == 0 %}
<i>No scheduled emails</i>
{% endif %}
{% for email in emails %}
<p>At {{ email.send_at }} <i>To: {% if email.recipient %}{{ email.recipient }}{% else %}All subscribers{% endif %}</i></p>
<b>{{ email.subject }}</b>
<iframe srcdoc="{{ email.content }}" width="100%" height="500px" style="background-color: white;"></iframe>
{% if not email.sent %}<a class="btn btn-outline-info" title="Edit this email" href="{% url 'retargeting:email' %}?id={{ email.id }}{% if email.recipient %}&u={{ email.recipient }}{% endif %}">Edit</a>{% endif %}
<hr>
{% endfor %}
{% endblock %}

retargeting/templates/retargeting/qrcode.html
{% extends 'base.html' %}
{% block head %}
<script type="text/javascript" src="/static/qrcode.min.js"></script>
{% endblock %}
{% block content %}
{% load feed_filters %}
<legend>{{ 'Generate a QR Code'|etrans }}</legend>
<p>{{ 'Supply a link in the form below to generate.'|etrans }}</p>
<input class="form-control mr-sm-2" type="text" placeholder="{{ base_url }}" aria-label="{{ base_url }}" id="text-input" autofocus>
<button onclick="downloadQr();" class="btn btn-primary" title="Download code">{{ 'Download'|etrans }}</button>
<hr>
<div style="display: flex; justify-content: space-around;"><div id="qrcode" style="border: 15px solid white; border-radius: 5px;"></div></div>
{% endblock %}
{% block javascript %}
var qrdiv = document.getElementById("qrcode");
var qr = new QRCode(qrdiv, "{{ base_url }}");
var image = qrdiv.querySelector('img');
image.style.width = "100%";
image.style.maxWidth = "400px";
const input = document.querySelector('#text-input');
var textValue = "{{ base_url }}";
var textUpdated = false;
input.addEventListener('input', (event) => {
	textValue = event.target.value;
	textUpdated = true;
});
setInterval(function() {
	if(textUpdated) {
		qr.makeCode(textValue);
		textUpdated = false;
	}
}, 1000);
function downloadImage(url, filename) {
  const link = document.createElement('a');
  link.href = url;
  link.download = '{{ the_site_name }} - ' + filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
function getBase64Image(img) {
                    var bsfcanvas = document.createElement("canvas");
                    bsfcanvas.width = img.clientWidth + 40;
                    bsfcanvas.height = img.clientHeight + 40;
                    var bsfctx = bsfcanvas.getContext("2d");
                    bsfctx.fillStyle = "#ffffff";
                    bsfctx.fillRect(0, 0, img.clientWidth + 40, img.clientHeight + 40);
                    bsfctx.drawImage(img, 20, 20, img.clientWidth, img.clientHeight);
                    var dataURL = bsfcanvas.toDataURL("image/png");
/*                    bsfcanvas.classList.add('hide');*/
                    return dataURL; /*.replace(/^data:image\/(png|jpg);base64,/, "");*/
                }
                function downloadQrImage(url, filename) {
                    const link = document.createElement('a');
                    link.download = '{{ the_site_name }} - ' + filename;
                    link.href = url;
                    link.classList.add('hide');
                    link.click();
                }
                function downloadQr(){
                    downloadQrImage(getBase64Image(document.getElementById('qrcode').querySelector('img')), 'QR Code.png');
                }
                /*{% include 'download_qr.js' %}*/
                qrdiv.onclick = downloadQr;
{% endblock %}

retargeting/templates/retargeting/retargeting_email.html
<h1>{{ site_name }} - Come back and visit me</h1>
<p>Dear {{ user.username }},</p>
<p>I noticed you created an account, and wanted to welcome you back for another visit. If you haven't already, you need to create an account to follow me, buy photos, tip and access more features on the site like live video and private shows.</p>
<p>Use this link to visit the site - <a href="{{ protocol }}://{{ domain }}">click here</a>.</p>
<p>Alternatively, you can paste the following link in your browser's address bar:</p>
<p>{{ protocol }}://{{ domain }}</p>
<p>Thanks for being a part of something awesome. I look forward to seeing you online.</p>
<p>Seeing you there with love,</p>
<p>Clementine</p>
{% autoescape off %}
<img style="width: 60%; max-width: 300px;" src="{{ photo }}" alt="A photo of me from {{ site_name }}"></img>
{% endautoescape %}

retargeting/templates/retargeting/retargeting_email_2.html
<h1>{{ site_name }} - See what's new in your next visit</h1>
<p>Dear {{ user.username }},</p>
<p>I'm inviting you back to see what's new on {{ site_name }}. I'd love to see you there!</p>
<p>Use this link to visit the site - <a href="{{ protocol }}://{{ domain }}">click here</a>.</p>
<p>Alternatively, you can paste the following link in your browser's address bar:</p>
<p>{{ protocol }}://{{ domain }}</p>
<p>It's great to see you here and spend time with you on the internet. I look forward to having you back!</p>
<p>Wishing you the best,</p>
<p>Clementine</p>
{% autoescape off %}
<img style="width: 60%; max-width: 300px;" src="{{ photo }}" alt="A photo of me from {{ site_name }}"></img>
{% endautoescape %}

retargeting/templates/retargeting/retargeting_email_3.html
<h1>{{ site_name }} - Spend some time with me online!</h1>
<p>Dear {{ user.username }},</p>
<p>I noticed you created an account a little while ago, and I would like to invite you back to spend some time with me. I'm always adding new features, content, and more to the site, so I'd love your feedback and to get to know you some more. Consider subscribing, buying a photo, or leaving a tip. Or just send me a message! If you haven't already, make sure to log in and verify your identity. It's really easy!</p>
<p>Use this link to visit the site - <a href="{{ protocol }}://{{ domain }}">click here</a>.</p>
<p>Alternatively, you can paste the following link in your browser's address bar:</p>
<p>{{ protocol }}://{{ domain }}</p>
<p>It's been a moment. Come back and see what's new, will you?</p>
<p>Let's get along,</p>
<p>Clementine</p>
{% autoescape off %}
<img style="width: 60%; max-width: 300px;" src="{{ photo }}" alt="A photo of me from {{ site_name }}"></img>
{% endautoescape %}

retargeting/templates/retargeting/routine_retargeting_email.html
<h1>{{ site_name }} - Your weekly email update</h1>
<p>Dear {{ user.username }},</p>
<p>So much is new on {{ site_name }}! I'd love to see you there. Come back and visit, we'll have fun together and get to know each other. There's always lots to see, like new photos, videos, blog posts, and livestreams. I can't wait to see you there!</p>
<p>Use this link to visit the site - <a href="{{ protocol }}://{{ domain }}">click here</a>.</p>
<p>Alternatively, you can paste the following link in your browser's address bar:</p>
<p>{{ protocol }}://{{ domain }}</p>
<p>Thanks for joining me. I look forward to seeing you there.</p>
<p>With love,</p>
<p>Clementine</p>
{% autoescape off %}
<img style="width: 60%; max-width: 300px;" src="{{ photo }}" alt="A photo of me from {{ site_name }}"></img>
{% endautoescape %}

retargeting/templates/retargeting/send_email.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<legend>Send Email</legend>
<p>Send an email to {% if request.GET.u %}{{ request.GET.u }}{% else %}all users{% endif %}. <a class="btn btn-outline-primary" title="See outgoing email" href="{% url 'retargeting:emails' %}">Outgoing</a></p>
<div style="width: 100%; max-width: 100%;">
<form method="POST" id="mail-form">
{% csrf_token %}
{% load feed_filters %}
{{ form.media }}
{{ form|crispy|safe }}
<button id="mail-submit" type="submit" class="btn btn-outline-danger">Send</button>
</div>
</form>
{% endblock %}
{% block javascript %}
$(document).ready(function() {
	document.getElementById('mail-form').addEventListener('submit', function(event) {
		document.getElementById('mail-submit').disabled = true;
	});
	$('#id_content_iframe').summernote({theme: 'bs5-dark'});
	#('#id_content_iframe').attr('style', 'background-color: #55555 !important;');
});
{% endblock %}